services:
  - type: web
    name: synsphere-backend
    runtime: java
    rootDir: backend
    plan: free
    region: singapore

    buildCommand: ./mvnw clean package -DskipTests

    startCommand: java -jar target/synergysphere-0.0.1-SNAPSHOT.jar

    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod