spring.application.name=synergysphere

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/synergysphere}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:Admin}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
# IMPORTANT: use validate (not update) since DB already exists

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=${JWT_SECRET:mysecretkeymysecretkeymysecretkey12}

server.port=${PORT:8081}

